//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Models.Article {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Article {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Article() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Models.Article.Article", typeof(Article).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 分类 的本地化字符串。
        /// </summary>
        public static string CateId {
            get {
                return ResourceManager.GetString("CateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E-mail 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email至多不超过30个字符 的本地化字符串。
        /// </summary>
        public static string Email_Length_Msg {
            get {
                return ResourceManager.GetString("Email_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段 的本地化字符串。
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 别名 的本地化字符串。
        /// </summary>
        public static string FieldRename {
            get {
                return ResourceManager.GetString("FieldRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否推荐 的本地化字符串。
        /// </summary>
        public static string IsCommend {
            get {
                return ResourceManager.GetString("IsCommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否首页置顶 的本地化字符串。
        /// </summary>
        public static string IsIndexTop {
            get {
                return ResourceManager.GetString("IsIndexTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否置顶 的本地化字符串。
        /// </summary>
        public static string IsTop {
            get {
                return ResourceManager.GetString("IsTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回复内容 的本地化字符串。
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面重命名 的本地化字符串。
        /// </summary>
        public static string ReName {
            get {
                return ResourceManager.GetString("ReName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面重命名至多不超过60个字符 的本地化字符串。
        /// </summary>
        public static string ReName_Length_Msg {
            get {
                return ResourceManager.GetString("ReName_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否允许评论 的本地化字符串。
        /// </summary>
        public static string ReplyPermit {
            get {
                return ResourceManager.GetString("ReplyPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面描述 的本地化字符串。
        /// </summary>
        public static string SeoDescription {
            get {
                return ResourceManager.GetString("SeoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面描述至多不超过1000个字符 的本地化字符串。
        /// </summary>
        public static string SeoDescription_Length_Msg {
            get {
                return ResourceManager.GetString("SeoDescription_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面关键字 的本地化字符串。
        /// </summary>
        public static string Seokeywords {
            get {
                return ResourceManager.GetString("Seokeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面关键字至多不超过500个字符 的本地化字符串。
        /// </summary>
        public static string Seokeywords_Length_Msg {
            get {
                return ResourceManager.GetString("Seokeywords_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面Metas 的本地化字符串。
        /// </summary>
        public static string SeoMetas {
            get {
                return ResourceManager.GetString("SeoMetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面Metas至多不超过1000个字符 的本地化字符串。
        /// </summary>
        public static string SeoMetas_Length_Msg {
            get {
                return ResourceManager.GetString("SeoMetas_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面Title 的本地化字符串。
        /// </summary>
        public static string SeoTitle {
            get {
                return ResourceManager.GetString("SeoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面Title至多不超过500个字符 的本地化字符串。
        /// </summary>
        public static string SeoTitle_Length_Msg {
            get {
                return ResourceManager.GetString("SeoTitle_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 摘要 的本地化字符串。
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 摘要至多不超过400个字符 的本地化字符串。
        /// </summary>
        public static string Summary_Length_Msg {
            get {
                return ResourceManager.GetString("Summary_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签 的本地化字符串。
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签至多不超过50个字符 的本地化字符串。
        /// </summary>
        public static string Tags_Length_Msg {
            get {
                return ResourceManager.GetString("Tags_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题至多不超过100个字符 的本地化字符串。
        /// </summary>
        public static string Title_Length_Msg {
            get {
                return ResourceManager.GetString("Title_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url 的本地化字符串。
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url至多不超过100个字符 的本地化字符串。
        /// </summary>
        public static string Url_Length_Msg {
            get {
                return ResourceManager.GetString("Url_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名至多不超过20个字符 的本地化字符串。
        /// </summary>
        public static string UserName_Length_Msg {
            get {
                return ResourceManager.GetString("UserName_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码 的本地化字符串。
        /// </summary>
        public static string ValidationCode {
            get {
                return ResourceManager.GetString("ValidationCode", resourceCulture);
            }
        }
    }
}
