//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Admin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Admin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Admin.Admin", typeof(Admin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增相册.
        /// </summary>
        public static string AddAlbum {
            get {
                return ResourceManager.GetString("AddAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增分类.
        /// </summary>
        public static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增内容.
        /// </summary>
        public static string AddContent {
            get {
                return ResourceManager.GetString("AddContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增成功.
        /// </summary>
        public static string AddedSuccessfully {
            get {
                return ResourceManager.GetString("AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理员.
        /// </summary>
        public static string Administrators {
            get {
                return ResourceManager.GetString("Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理员列表.
        /// </summary>
        public static string Administratorslist {
            get {
                return ResourceManager.GetString("Administratorslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相册.
        /// </summary>
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相册评论.
        /// </summary>
        public static string AlbumComment {
            get {
                return ResourceManager.GetString("AlbumComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相册修改.
        /// </summary>
        public static string AlbumsEdits {
            get {
                return ResourceManager.GetString("AlbumsEdits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允许评论.
        /// </summary>
        public static string AllowComments {
            get {
                return ResourceManager.GetString("AllowComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 匿名.
        /// </summary>
        public static string Anonymous {
            get {
                return ResourceManager.GetString("Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文章.
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文章评论.
        /// </summary>
        public static string ArticleComment {
            get {
                return ResourceManager.GetString("ArticleComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 升序.
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示比例.
        /// </summary>
        public static string AspectRatio {
            get {
                return ResourceManager.GetString("AspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 至少有一个选中项.
        /// </summary>
        public static string Atleastone {
            get {
                return ResourceManager.GetString("Atleastone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基础信息.
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基础设置.
        /// </summary>
        public static string BasisSet {
            get {
                return ResourceManager.GetString("BasisSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批量删除文章.
        /// </summary>
        public static string BatchDeleteArticle {
            get {
                return ResourceManager.GetString("BatchDeleteArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面中调用.
        /// </summary>
        public static string Called {
            get {
                return ResourceManager.GetString("Called", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消管理员权限.
        /// </summary>
        public static string CancelManagement {
            get {
                return ResourceManager.GetString("CancelManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分类.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定删除当前分类及其子项？.
        /// </summary>
        public static string CategoryDel_Tip {
            get {
                return ResourceManager.GetString("CategoryDel_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分类信息.
        /// </summary>
        public static string CategoryInfo {
            get {
                return ResourceManager.GetString("CategoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置分类信息.
        /// </summary>
        public static string CategoryReset {
            get {
                return ResourceManager.GetString("CategoryReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分类设置.
        /// </summary>
        public static string CategorySettings {
            get {
                return ResourceManager.GetString("CategorySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 评论.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置管理.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定执行？.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容列表.
        /// </summary>
        public static string ContentList {
            get {
                return ResourceManager.GetString("ContentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容管理.
        /// </summary>
        public static string ContentManagement {
            get {
                return ResourceManager.GetString("ContentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 继续修改.
        /// </summary>
        public static string ContinueModify {
            get {
                return ResourceManager.GetString("ContinueModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 投稿.
        /// </summary>
        public static string Contributors {
            get {
                return ResourceManager.GetString("Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 国家.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单选按钮选中表示设为封面.
        /// </summary>
        public static string Cover_Tip {
            get {
                return ResourceManager.GetString("Cover_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生成.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义区域[首页].
        /// </summary>
        public static string CustomArea {
            get {
                return ResourceManager.GetString("CustomArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义区域[全网].
        /// </summary>
        public static string CustomGlobalArea {
            get {
                return ResourceManager.GetString("CustomGlobalArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日期.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束日期必须大于起始日期.
        /// </summary>
        public static string DateCompare {
            get {
                return ResourceManager.GetString("DateCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认语言必须在多语言设置被选中.
        /// </summary>
        public static string DefaultLangSet {
            get {
                return ResourceManager.GetString("DefaultLangSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认删除？.
        /// </summary>
        public static string Delete_Tip {
            get {
                return ResourceManager.GetString("Delete_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除账号.
        /// </summary>
        public static string Deleteaccount {
            get {
                return ResourceManager.GetString("Deleteaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除文章.
        /// </summary>
        public static string DeleteArticle {
            get {
                return ResourceManager.GetString("DeleteArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除成功.
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败.
        /// </summary>
        public static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除选中项.
        /// </summary>
        public static string DeleteSelected {
            get {
                return ResourceManager.GetString("DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认删除选中项？.
        /// </summary>
        public static string DeleteSelected_Tip {
            get {
                return ResourceManager.GetString("DeleteSelected_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除用户.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 降序.
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 草稿.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮件发送设置.
        /// </summary>
        public static string EmailSet {
            get {
                return ResourceManager.GetString("EmailSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扩展字段.
        /// </summary>
        public static string ExtensionField {
            get {
                return ResourceManager.GetString("ExtensionField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扩展信息.
        /// </summary>
        public static string ExtensionInfo {
            get {
                return ResourceManager.GetString("ExtensionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扩展字段.
        /// </summary>
        public static string ExtensionSet {
            get {
                return ResourceManager.GetString("ExtensionSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 筛选.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 论坛.
        /// </summary>
        public static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 论坛配置.
        /// </summary>
        public static string ForumConfiguration {
            get {
                return ResourceManager.GetString("ForumConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面批量生成.
        /// </summary>
        public static string Generatepages {
            get {
                return ResourceManager.GetString("Generatepages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生成成功.
        /// </summary>
        public static string GenerateSuccess {
            get {
                return ResourceManager.GetString("GenerateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生成中....
        /// </summary>
        public static string Generating {
            get {
                return ResourceManager.GetString("Generating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生成管理.
        /// </summary>
        public static string GeneratingManagement {
            get {
                return ResourceManager.GetString("GeneratingManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首页.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id号.
        /// </summary>
        public static string IDnumber {
            get {
                return ResourceManager.GetString("IDnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 立即发布.
        /// </summary>
        public static string ImmediateRelease {
            get {
                return ResourceManager.GetString("ImmediateRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 多语言js文件生成.
        /// </summary>
        public static string JsLangGenerate {
            get {
                return ResourceManager.GetString("JsLangGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一次登录.
        /// </summary>
        public static string LastloginDate {
            get {
                return ResourceManager.GetString("LastloginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交中....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前位置.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录用户.
        /// </summary>
        public static string LoggedUser {
            get {
                return ResourceManager.GetString("LoggedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登出.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 后台管理.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理首页.
        /// </summary>
        public static string ManagementHome {
            get {
                return ResourceManager.GetString("ManagementHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分类手动管理.
        /// </summary>
        public static string ManualManagement {
            get {
                return ResourceManager.GetString("ManualManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改失败, 格式不符合要求.
        /// </summary>
        public static string ModificationFailed {
            get {
                return ResourceManager.GetString("ModificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改成功.
        /// </summary>
        public static string ModifiedSuccessfully {
            get {
                return ResourceManager.GetString("ModifiedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改分类.
        /// </summary>
        public static string ModifyCategory {
            get {
                return ResourceManager.GetString("ModifyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改配置信息.
        /// </summary>
        public static string ModifyConfiguration {
            get {
                return ResourceManager.GetString("ModifyConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改内容.
        /// </summary>
        public static string ModifyContent {
            get {
                return ResourceManager.GetString("ModifyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改失败.
        /// </summary>
        public static string ModifyFailed {
            get {
                return ResourceManager.GetString("ModifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 多语言设置.
        /// </summary>
        public static string MultiLangSet {
            get {
                return ResourceManager.GetString("MultiLangSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必选，请先在&quot;配置管理&quot;--&quot;分类设置&quot;处添加分类信息.
        /// </summary>
        public static string MustCateId {
            get {
                return ResourceManager.GetString("MustCateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网络故障.
        /// </summary>
        public static string NetworkFailure {
            get {
                return ResourceManager.GetString("NetworkFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外网无法访问.
        /// </summary>
        public static string NetworkNoAccessed {
            get {
                return ResourceManager.GetString("NetworkNoAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 否.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不允许评论.
        /// </summary>
        public static string NoComments {
            get {
                return ResourceManager.GetString("NoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不限.
        /// </summary>
        public static string Nolimited {
            get {
                return ResourceManager.GetString("Nolimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不限.
        /// </summary>
        public static string Nolimited1 {
            get {
                return ResourceManager.GetString("Nolimited1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不推荐.
        /// </summary>
        public static string NoRecommended {
            get {
                return ResourceManager.GetString("NoRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正常.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不显示.
        /// </summary>
        public static string NoShow {
            get {
                return ResourceManager.GetString("NoShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不置顶.
        /// </summary>
        public static string NoSticky {
            get {
                return ResourceManager.GetString("NoSticky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 留言.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        public static string Operating {
            get {
                return ResourceManager.GetString("Operating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作失败.
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作未能成功执行，请稍后再试或提交反馈至YQHome.net，可能的原因.
        /// </summary>
        public static string OperationFailed1 {
            get {
                return ResourceManager.GetString("OperationFailed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作成功.
        /// </summary>
        public static string OperationSuccessful {
            get {
                return ResourceManager.GetString("OperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面重命名不能全为数字.
        /// </summary>
        public static string PageRenameTip {
            get {
                return ResourceManager.GetString("PageRenameTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帖子.
        /// </summary>
        public static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 区间.
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 推荐.
        /// </summary>
        public static string Recommend {
            get {
                return ResourceManager.GetString("Recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册日期.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相对地址.
        /// </summary>
        public static string RelativeAddress {
            get {
                return ResourceManager.GetString("RelativeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除管理.
        /// </summary>
        public static string Removetheadministrator {
            get {
                return ResourceManager.GetString("Removetheadministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回帖.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转载配置.
        /// </summary>
        public static string ReproducedConfiguration {
            get {
                return ResourceManager.GetString("ReproducedConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新生成缩略图.
        /// </summary>
        public static string ResetThumbnail {
            get {
                return ResourceManager.GetString("ResetThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved.
        /// </summary>
        public static string Rights {
            get {
                return ResourceManager.GetString("Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存草稿.
        /// </summary>
        public static string SaveDraft {
            get {
                return ResourceManager.GetString("SaveDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选取图片.
        /// </summary>
        public static string SelectPhotos {
            get {
                return ResourceManager.GetString("SelectPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择子分类.
        /// </summary>
        public static string SelectSubcategories {
            get {
                return ResourceManager.GetString("SelectSubcategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO.
        /// </summary>
        public static string SEO {
            get {
                return ResourceManager.GetString("SEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设为管理员.
        /// </summary>
        public static string SetAsAdmin {
            get {
                return ResourceManager.GetString("SetAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设为管理.
        /// </summary>
        public static string Settoadministrator {
            get {
                return ResourceManager.GetString("Settoadministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单页.
        /// </summary>
        public static string SinglePage {
            get {
                return ResourceManager.GetString("SinglePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单页评论.
        /// </summary>
        public static string SinglePageComment {
            get {
                return ResourceManager.GetString("SinglePageComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 站点描述.
        /// </summary>
        public static string SiteDescription {
            get {
                return ResourceManager.GetString("SiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gmail:587,其它:25.
        /// </summary>
        public static string SmtpPortTip {
            get {
                return ResourceManager.GetString("SmtpPortTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 例如: smtp.gmail.com.
        /// </summary>
        public static string SmtpServerTip {
            get {
                return ResourceManager.GetString("SmtpServerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排序.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 静态化设置.
        /// </summary>
        public static string StaticSet {
            get {
                return ResourceManager.GetString("StaticSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下子分类.
        /// </summary>
        public static string Subcategories {
            get {
                return ResourceManager.GetString("Subcategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交到.
        /// </summary>
        public static string SubmittedTo {
            get {
                return ResourceManager.GetString("SubmittedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作成功。.
        /// </summary>
        public static string Success_Tip {
            get {
                return ResourceManager.GetString("Success_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标签.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme by.
        /// </summary>
        public static string ThemeBy {
            get {
                return ResourceManager.GetString("ThemeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 格式要求：(例如 200x150,90x60).
        /// </summary>
        public static string ThumbnailInfoTip {
            get {
                return ResourceManager.GetString("ThumbnailInfoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标题.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 置顶.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总计.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 恢复删除.
        /// </summary>
        public static string Undelete {
            get {
                return ResourceManager.GetString("Undelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有选取任何图片.
        /// </summary>
        public static string Upload_Tip {
            get {
                return ResourceManager.GetString("Upload_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择文件.
        /// </summary>
        public static string UploadFile_Tip1 {
            get {
                return ResourceManager.GetString("UploadFile_Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传目录不存在.
        /// </summary>
        public static string UploadFile_Tip2 {
            get {
                return ResourceManager.GetString("UploadFile_Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传文件大小超过限制.
        /// </summary>
        public static string UploadFile_Tip3 {
            get {
                return ResourceManager.GetString("UploadFile_Tip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传文件扩展名是不允许的扩展名.
        /// </summary>
        public static string UploadFile_Tip4 {
            get {
                return ResourceManager.GetString("UploadFile_Tip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分类用户界面管理.
        /// </summary>
        public static string UserInterface {
            get {
                return ResourceManager.GetString("UserInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户列表.
        /// </summary>
        public static string Userlist {
            get {
                return ResourceManager.GetString("Userlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户管理.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册用户.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可用{year}{month}{day}表示当前年，月，日.
        /// </summary>
        public static string WebStaticFolderTip {
            get {
                return ResourceManager.GetString("WebStaticFolderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
