//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Models.Account {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Models.Account.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 生日 的本地化字符串。
        /// </summary>
        public static string Birth {
            get {
                return ResourceManager.GetString("Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认新密码 的本地化字符串。
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码和确认密码不匹配。 的本地化字符串。
        /// </summary>
        public static string ConfirmPassword_Compare_Msg {
            get {
                return ResourceManager.GetString("ConfirmPassword_Compare_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮件地址 的本地化字符串。
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回复通知Email 的本地化字符串。
        /// </summary>
        public static string EmailNotice {
            get {
                return ResourceManager.GetString("EmailNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Facebook 的本地化字符串。
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人简介 的本地化字符串。
        /// </summary>
        public static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否發送回复提醒郵件 的本地化字符串。
        /// </summary>
        public static string IsSendEmail {
            get {
                return ResourceManager.GetString("IsSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所在地 的本地化字符串。
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 荣誉 的本地化字符串。
        /// </summary>
        public static string Medals {
            get {
                return ResourceManager.GetString("Medals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码 的本地化字符串。
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码必须至少包含6个字符。 的本地化字符串。
        /// </summary>
        public static string NewPassword_Length_Msg {
            get {
                return ResourceManager.GetString("NewPassword_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昵称 的本地化字符串。
        /// </summary>
        public static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前密码 的本地化字符串。
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码必须至少包含6个字符。 的本地化字符串。
        /// </summary>
        public static string Password_Length_Msg {
            get {
                return ResourceManager.GetString("Password_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话 的本地化字符串。
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQ 的本地化字符串。
        /// </summary>
        public static string QQ {
            get {
                return ResourceManager.GetString("QQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住我? 的本地化字符串。
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人签名 的本地化字符串。
        /// </summary>
        public static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新浪微博 的本地化字符串。
        /// </summary>
        public static string Sina {
            get {
                return ResourceManager.GetString("Sina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Twitter 的本地化字符串。
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息 的本地化字符串。
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人网站 的本地化字符串。
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
