//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Web {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Web() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Web", typeof(Web).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发表评论.
        /// </summary>
        public static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发表留言.
        /// </summary>
        public static string AddNote {
            get {
                return ResourceManager.GetString("AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相册评论.
        /// </summary>
        public static string AlbumComments {
            get {
                return ResourceManager.GetString("AlbumComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相册.
        /// </summary>
        public static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相册查看.
        /// </summary>
        public static string AlbumView {
            get {
                return ResourceManager.GetString("AlbumView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 归档.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文章评论.
        /// </summary>
        public static string ArticleComments {
            get {
                return ResourceManager.GetString("ArticleComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文章.
        /// </summary>
        public static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基础信息.
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生日.
        /// </summary>
        public static string Birth {
            get {
                return ResourceManager.GetString("Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改密码.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新验证码.
        /// </summary>
        public static string ChangeValidationCode {
            get {
                return ResourceManager.GetString("ChangeValidationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 推荐.
        /// </summary>
        public static string Commend {
            get {
                return ResourceManager.GetString("Commend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 评论.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 评论回复提醒邮件.
        /// </summary>
        public static string CommentReplyEmail {
            get {
                return ResourceManager.GetString("CommentReplyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 评论.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认密码.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除评论.
        /// </summary>
        public static string DeleteComment {
            get {
                return ResourceManager.GetString("DeleteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除留言.
        /// </summary>
        public static string DeleteNote {
            get {
                return ResourceManager.GetString("DeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定删除选中项?.
        /// </summary>
        public static string DeleteTip_AreUSureDelete {
            get {
                return ResourceManager.GetString("DeleteTip_AreUSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不发送.
        /// </summary>
        public static string Donotsend {
            get {
                return ResourceManager.GetString("Donotsend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性别.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首页.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简介.
        /// </summary>
        public static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送回复提醒邮件.
        /// </summary>
        public static string IsSendEmail {
            get {
                return ResourceManager.GetString("IsSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zh-cn.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新评论.
        /// </summary>
        public static string LatestComments {
            get {
                return ResourceManager.GetString("LatestComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 列表查看.
        /// </summary>
        public static string ListView {
            get {
                return ResourceManager.GetString("ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位置.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号信息.
        /// </summary>
        public static string LogOn_AccountInfo {
            get {
                return ResourceManager.GetString("LogOn_AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记住我?.
        /// </summary>
        public static string LogOn_RememberMe {
            get {
                return ResourceManager.GetString("LogOn_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入您的用户名及密码，如果你还没有账号，请.
        /// </summary>
        public static string LogOn_Tip {
            get {
                return ResourceManager.GetString("LogOn_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名或密码错误.
        /// </summary>
        public static string LogOn_UsernameOrPwdError {
            get {
                return ResourceManager.GetString("LogOn_UsernameOrPwdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登出.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改信息.
        /// </summary>
        public static string ModifyInformation {
            get {
                return ResourceManager.GetString("ModifyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改用户信息.
        /// </summary>
        public static string ModifyUserInfo {
            get {
                return ResourceManager.GetString("ModifyUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必须登录.
        /// </summary>
        public static string MustLogIn {
            get {
                return ResourceManager.GetString("MustLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的评论.
        /// </summary>
        public static string MyComments {
            get {
                return ResourceManager.GetString("MyComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的留言.
        /// </summary>
        public static string MyMessages {
            get {
                return ResourceManager.GetString("MyMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首页.
        /// </summary>
        public static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新评论.
        /// </summary>
        public static string NewComments {
            get {
                return ResourceManager.GetString("NewComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新密码.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昵称.
        /// </summary>
        public static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 否.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有数据.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有了.
        /// </summary>
        public static string NoMore {
            get {
                return ResourceManager.GetString("NoMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 留言.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 留言回复提醒邮件.
        /// </summary>
        public static string NoteReplyEmail {
            get {
                return ResourceManager.GetString("NoteReplyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 留言.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旧密码.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旧密码错误.
        /// </summary>
        public static string OldPasswordWrong {
            get {
                return ResourceManager.GetString("OldPasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 张.
        /// </summary>
        public static string OnePhoto {
            get {
                return ResourceManager.GetString("OnePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 或者.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电话.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请.
        /// </summary>
        public static string Please {
            get {
                return ResourceManager.GetString("Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发表于.
        /// </summary>
        public static string PostedOn {
            get {
                return ResourceManager.GetString("PostedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QQ.
        /// </summary>
        public static string Qq {
            get {
                return ResourceManager.GetString("Qq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re.
        /// </summary>
        public static string Re {
            get {
                return ResourceManager.GetString("Re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建新账号.
        /// </summary>
        public static string Register_CreateNewAccount {
            get {
                return ResourceManager.GetString("Register_CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用下面的表单创建账号,密码不能少于6个字符.
        /// </summary>
        public static string Register_Tip {
            get {
                return ResourceManager.GetString("Register_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名已存在, 请输入不同的用户名.
        /// </summary>
        public static string Register_UsernameExists {
            get {
                return ResourceManager.GetString("Register_UsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回复.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置为默认.
        /// </summary>
        public static string RestoreDefault {
            get {
                return ResourceManager.GetString("RestoreDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文章.
        /// </summary>
        public static string Rss {
            get {
                return ResourceManager.GetString("Rss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索关键字.
        /// </summary>
        public static string SearchKey {
            get {
                return ResourceManager.GetString("SearchKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 张.
        /// </summary>
        public static string SeveralPhotos {
            get {
                return ResourceManager.GetString("SeveralPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 统计.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统错误.
        /// </summary>
        public static string SysError {
            get {
                return ResourceManager.GetString("SysError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标签.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模板设置.
        /// </summary>
        public static string ThemeSetting {
            get {
                return ResourceManager.GetString("ThemeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条.
        /// </summary>
        public static string Tiao {
            get {
                return ResourceManager.GetString("Tiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码修改成功.
        /// </summary>
        public static string Tip_ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("Tip_ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该楼已经被删除.
        /// </summary>
        public static string Tip_ThisFloorBeenDeleted {
            get {
                return ResourceManager.GetString("Tip_ThisFloorBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 置顶.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 评论最多.
        /// </summary>
        public static string TopComments {
            get {
                return ResourceManager.GetString("TopComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览最多.
        /// </summary>
        public static string TopView {
            get {
                return ResourceManager.GetString("TopView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传头像.
        /// </summary>
        public static string UploadAvatar {
            get {
                return ResourceManager.GetString("UploadAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人主页.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户中心.
        /// </summary>
        public static string UserCenter {
            get {
                return ResourceManager.GetString("UserCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户信息.
        /// </summary>
        public static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证码.
        /// </summary>
        public static string ValidationCode {
            get {
                return ResourceManager.GetString("ValidationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证码输入错误.
        /// </summary>
        public static string ValidationCodeError {
            get {
                return ResourceManager.GetString("ValidationCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看详情.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 踩.
        /// </summary>
        public static string Vote_Down {
            get {
                return ResourceManager.GetString("Vote_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 投票成功.
        /// </summary>
        public static string Vote_Tip_Success {
            get {
                return ResourceManager.GetString("Vote_Tip_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你已经投过票.
        /// </summary>
        public static string Vote_Tip_Voted {
            get {
                return ResourceManager.GetString("Vote_Tip_Voted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顶.
        /// </summary>
        public static string Vote_Up {
            get {
                return ResourceManager.GetString("Vote_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主页.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 微薄.
        /// </summary>
        public static string Weibo {
            get {
                return ResourceManager.GetString("Weibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
