//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Js {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Js.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 评论.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 评论.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认密码不能为空.
        /// </summary>
        public static string ConfirmPasswordCanNotBeEmpty {
            get {
                return ResourceManager.GetString("ConfirmPasswordCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 两次填写的密码不一致.
        /// </summary>
        public static string ConfirmPasswordNotEqual {
            get {
                return ResourceManager.GetString("ConfirmPasswordNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容不能为空.
        /// </summary>
        public static string ContentCanNotEmpty {
            get {
                return ResourceManager.GetString("ContentCanNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email不能为空.
        /// </summary>
        public static string EmailCanNotBeEmpty {
            get {
                return ResourceManager.GetString("EmailCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email格式错误.
        /// </summary>
        public static string EmailFormatInvalid {
            get {
                return ResourceManager.GetString("EmailFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新密码不能为空.
        /// </summary>
        public static string NewPasswordCanNotEmpty {
            get {
                return ResourceManager.GetString("NewPasswordCanNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旧密码不能为空.
        /// </summary>
        public static string OldPasswordCanNotEmpty {
            get {
                return ResourceManager.GetString("OldPasswordCanNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码不能为空.
        /// </summary>
        public static string PasswordCanNotBeEmpty {
            get {
                return ResourceManager.GetString("PasswordCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码不能少于6个字符.
        /// </summary>
        public static string PasswordLengthLimit {
            get {
                return ResourceManager.GetString("PasswordLengthLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条.
        /// </summary>
        public static string Tiao {
            get {
                return ResourceManager.GetString("Tiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名不能为空.
        /// </summary>
        public static string UserNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("UserNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览.
        /// </summary>
        public static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
    }
}
