//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Models.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Web {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Web() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Models.Web.Web", typeof(Web).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱.
        /// </summary>
        public static string AdminEmail {
            get {
                return ResourceManager.GetString("AdminEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yq.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文章列表分页记录数.
        /// </summary>
        public static string CatePagerCount {
            get {
                return ResourceManager.GetString("CatePagerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字符.
        /// </summary>
        public static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 评论分页记录数.
        /// </summary>
        public static string CommentPagerCount {
            get {
                return ResourceManager.GetString("CommentPagerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 格式错误.
        /// </summary>
        public static string Common_Reg_Msg {
            get {
                return ResourceManager.GetString("Common_Reg_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必须填写.
        /// </summary>
        public static string Common_Required_Msg {
            get {
                return ResourceManager.GetString("Common_Required_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by &lt;a href=&quot;http://www.yqhome.net/&quot; target=&quot;_blank&quot;&gt;YqBlog&lt;/a&gt;.
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天前.
        /// </summary>
        public static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插图总数.
        /// </summary>
        public static string DecorateImgCount {
            get {
                return ResourceManager.GetString("DecorateImgCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认语言.
        /// </summary>
        public static string DefaultLang {
            get {
                return ResourceManager.GetString("DefaultLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 女.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 论坛帖子列表分页记录数.
        /// </summary>
        public static string ForumPagerCount {
            get {
                return ResourceManager.GetString("ForumPagerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小时前.
        /// </summary>
        public static string HoursAgo {
            get {
                return ResourceManager.GetString("HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备案号.
        /// </summary>
        public static string Icp {
            get {
                return ResourceManager.GetString("Icp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否生成文章html页.
        /// </summary>
        public static string IfHtmlCreated {
            get {
                return ResourceManager.GetString("IfHtmlCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 多语言网站内容独立.
        /// </summary>
        public static string IfIndependentContentViaLang {
            get {
                return ResourceManager.GetString("IfIndependentContentViaLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否异步分页.
        /// </summary>
        public static string IfPagingAjax {
            get {
                return ResourceManager.GetString("IfPagingAjax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否发送回复提醒邮件.
        /// </summary>
        public static string IfSendReplyEmail {
            get {
                return ResourceManager.GetString("IfSendReplyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否启用验证码.
        /// </summary>
        public static string IfValidateCode {
            get {
                return ResourceManager.GetString("IfValidateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否启用静态url.
        /// </summary>
        public static string IfWebStatic {
            get {
                return ResourceManager.GetString("IfWebStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首页分页记录数.
        /// </summary>
        public static string IndexPagerCount {
            get {
                return ResourceManager.GetString("IndexPagerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zh-cn.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 长度.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网站Logo (相对地址).
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 男.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 截取为摘要信息的最大字符数.
        /// </summary>
        public static string MaxSummaryCount {
            get {
                return ResourceManager.GetString("MaxSummaryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分钟前.
        /// </summary>
        public static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必须为数字.
        /// </summary>
        public static string MustNum {
            get {
                return ResourceManager.GetString("MustNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一页.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 留言分页记录数.
        /// </summary>
        public static string NotePagerCount {
            get {
                return ResourceManager.GetString("NotePagerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一页.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        public static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒前.
        /// </summary>
        public static string SecAgo {
            get {
                return ResourceManager.GetString("SecAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保密.
        /// </summary>
        public static string Secrecy {
            get {
                return ResourceManager.GetString("Secrecy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string SmtpPass {
            get {
                return ResourceManager.GetString("SmtpPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 端口.
        /// </summary>
        public static string SmtpPort {
            get {
                return ResourceManager.GetString("SmtpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮件服务器.
        /// </summary>
        public static string SmtpServer {
            get {
                return ResourceManager.GetString("SmtpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号.
        /// </summary>
        public static string SmtpUser {
            get {
                return ResourceManager.GetString("SmtpUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字符串.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文本.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认风格.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 论坛帖子展示分页记录数.
        /// </summary>
        public static string ThreadPagerCount {
            get {
                return ResourceManager.GetString("ThreadPagerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 格式错误.
        /// </summary>
        public static string ThumbnailFormat {
            get {
                return ResourceManager.GetString("ThumbnailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相册缩略图设置.
        /// </summary>
        public static string ThumbnailInfo {
            get {
                return ResourceManager.GetString("ThumbnailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户权限.
        /// </summary>
        public static string UserPermission {
            get {
                return ResourceManager.GetString("UserPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容设定.
        /// </summary>
        public static string WebContentLang {
            get {
                return ResourceManager.GetString("WebContentLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网站简介.
        /// </summary>
        public static string WebDescription {
            get {
                return ResourceManager.GetString("WebDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 多语言设置.
        /// </summary>
        public static string WebLangs {
            get {
                return ResourceManager.GetString("WebLangs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 站点路径.
        /// </summary>
        public static string WebPath {
            get {
                return ResourceManager.GetString("WebPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 静态化目录.
        /// </summary>
        public static string WebStaticFolder {
            get {
                return ResourceManager.GetString("WebStaticFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网站名称.
        /// </summary>
        public static string Webtitle {
            get {
                return ResourceManager.GetString("Webtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网站URL.
        /// </summary>
        public static string Weburl {
            get {
                return ResourceManager.GetString("Weburl", resourceCulture);
            }
        }
    }
}
